// This file has been autogenerated from a class added in the UI designer.

using System;
using AgileBits;
using Foundation;
using UIKit;

namespace DemoOnePasswordExtension
{
	public partial class RegisterViewController : UIViewController
	{
		public RegisterViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			this.onePasswordButton.Hidden = !OnePasswordExtension.SharedExtension.IsAppExtensionAvailable;
		}

		partial void saveLoginToOnePassword(Foundation.NSObject sender)
		{
			NSDictionary newLoginDetails = new NSDictionary(
				AppExtensionLoginDictionarykeys.TitleKey, "ACME",
				AppExtensionLoginDictionarykeys.UsernameKey, this.usernameTextField.Text ?? "",
				AppExtensionLoginDictionarykeys.PasswordKey, this.passwordTextField.Text ?? "",
				AppExtensionLoginDictionarykeys.NotesKey, "Saved with the ACME app",
				AppExtensionLoginDictionarykeys.SectionTitleKey, "ACME Browser",
				AppExtensionLoginDictionarykeys.FieldsKey, new NSDictionary("firstname", this.firstnameTextField.Text ?? "",
																"lastname", this.lastnameTextField.Text ?? "")
			);

			// The password generation options are optional, but are very handy in case you have strict rules about password lengths, symbols and digits.
			NSDictionary passwordGenerationOptions = new NSDictionary(
				// The minimum password length can be 4 or more.
				AppExtensionPasswordGeneratorOptions.MinLengthKey, 8,

				// The maximum password length can be 50 or less.
				AppExtensionPasswordGeneratorOptions.MaxLengthKey, 30,

				// If YES, the 1Password will guarantee that the generated password will contain at least one digit (number between 0 and 9). Passing NO will not exclude digits from the generated password.
				AppExtensionPasswordGeneratorOptions.RequireDigitsKey, true,

				// If YES, the 1Password will guarantee that the generated password will contain at least one symbol (See the list bellow). Passing NO with will exclude symbols from the generated password.
				AppExtensionPasswordGeneratorOptions.RequireSymbolsKey, true,

				// Here are all the symbols available in the the 1Password Password Generator:
				// !#$%^&*()_-+=|[]{}'\";.,>?/~`
				// The string for AppExtensionPasswordGeneratorOptions.ForbiddenCharactersKey should contain the symbols and characters that you wish 1Password to exclude from the generated password.
				AppExtensionPasswordGeneratorOptions.ForbiddenCharactersKey, "!#$%/0lIO"
			);
			OnePasswordExtension.SharedExtension.StoreLoginForURLString("https://www.acme.com", newLoginDetails, passwordGenerationOptions, this, sender, (NSDictionary loginDictionary, NSError error) =>
			{
				if (loginDictionary == null || loginDictionary.Count == 0)
				{
					if (error.Code != AppExtensionErrorCodes.CancelledByUser)
					{
						System.Diagnostics.Debug.WriteLine("Failed to use 1Password App Extension to save a new Login: {0}", error);
					}
					return;
				}

				this.usernameTextField.Text = (NSString)loginDictionary[AppExtensionLoginDictionarykeys.UsernameKey] ?? "";
				this.passwordTextField.Text = (NSString)loginDictionary[AppExtensionLoginDictionarykeys.PasswordKey] ?? "";
				this.firstnameTextField.Text = (NSString)((NSDictionary)loginDictionary[AppExtensionLoginDictionarykeys.ReturnedFieldsKey])["firstname"] ?? "";
				this.lastnameTextField.Text = (NSString)((NSDictionary)loginDictionary[AppExtensionLoginDictionarykeys.ReturnedFieldsKey])["lastname"] ?? "";
				// retrieve any additional fields that were passed in newLoginDetails dictionary
			});
		}
	}
}
