// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DemoOnePasswordExtension
{
	public partial class ThankYouViewController : UIViewController
	{
		public ThankYouViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
